-- Auto-generated migration for CommTrainer solo tables
-- Paste this into: https://supabase.com/dashboard/project/rumvtsrhzbckmzfujmmo/sql/new


CREATE TABLE IF NOT EXISTS solo_industries (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    icon TEXT NOT NULL DEFAULT '',
    roles JSONB NOT NULL DEFAULT '[]'
);

CREATE TABLE IF NOT EXISTS solo_scenarios (
    id TEXT PRIMARY KEY,
    industry TEXT NOT NULL REFERENCES solo_industries(id) ON DELETE CASCADE,
    skill TEXT NOT NULL,
    title TEXT NOT NULL,
    goal TEXT NOT NULL DEFAULT '',
    difficulty INTEGER NOT NULL DEFAULT 2,
    duration_min INTEGER NOT NULL DEFAULT 5,
    xp_reward INTEGER NOT NULL DEFAULT 10,
    coin_reward INTEGER NOT NULL DEFAULT 5,
    ai_persona TEXT NOT NULL DEFAULT '',
    patient_type TEXT,
    emoji TEXT,
    script JSONB NOT NULL DEFAULT '[]',
    feedback JSONB NOT NULL DEFAULT '{}'
);

CREATE TABLE IF NOT EXISTS daily_suggestions (
    id TEXT PRIMARY KEY,
    industry TEXT NOT NULL REFERENCES solo_industries(id) ON DELETE CASCADE,
    skill TEXT NOT NULL,
    title TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    price INTEGER NOT NULL DEFAULT 0,
    emoji TEXT NOT NULL DEFAULT '⭐',
    difficulty INTEGER NOT NULL DEFAULT 2,
    duration_min INTEGER NOT NULL DEFAULT 5,
    patient_type TEXT
);

CREATE TABLE IF NOT EXISTS solo_quests (
    id TEXT PRIMARY KEY,
    text TEXT NOT NULL,
    reward INTEGER NOT NULL DEFAULT 10,
    type TEXT NOT NULL DEFAULT 'communication',
    target_skill TEXT
);

CREATE TABLE IF NOT EXISTS user_progress (
    user_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    name TEXT NOT NULL DEFAULT '',
    primary_industry TEXT NOT NULL DEFAULT 'medicine',
    role TEXT NOT NULL DEFAULT '',
    goal TEXT NOT NULL DEFAULT '',
    additional_industries JSONB NOT NULL DEFAULT '[]',
    streak INTEGER NOT NULL DEFAULT 0,
    xp INTEGER NOT NULL DEFAULT 0,
    coins INTEGER NOT NULL DEFAULT 0,
    notifications INTEGER NOT NULL DEFAULT 0,
    mode TEXT NOT NULL DEFAULT 'keyboard',
    quest_done_date TEXT NOT NULL DEFAULT '',
    focus_done_date TEXT NOT NULL DEFAULT '',
    purchased_suggestion_ids JSONB NOT NULL DEFAULT '[]',
    completed JSONB NOT NULL DEFAULT '{}',
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS solo_attempts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    scenario_id TEXT NOT NULL REFERENCES solo_scenarios(id) ON DELETE CASCADE,
    rating INTEGER NOT NULL DEFAULT 0,
    xp_gained INTEGER NOT NULL DEFAULT 0,
    coins_gained INTEGER NOT NULL DEFAULT 0,
    transcript JSONB NOT NULL DEFAULT '[]',
    created_at TIMESTAMPTZ DEFAULT NOW()
);


-- Seed industries
INSERT INTO solo_industries (id, name, icon, roles) VALUES ('medicine', 'Медицина', '🏥', '["Врач", "Медсестра", "Диспетчер"]') ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, icon=EXCLUDED.icon, roles=EXCLUDED.roles;
INSERT INTO solo_industries (id, name, icon, roles) VALUES ('psychology', 'Психология', '🧠', '["Психолог", "Соцработник"]') ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, icon=EXCLUDED.icon, roles=EXCLUDED.roles;
INSERT INTO solo_industries (id, name, icon, roles) VALUES ('education', 'Образование', '🎓', '["Преподаватель", "Куратор", "Методист"]') ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, icon=EXCLUDED.icon, roles=EXCLUDED.roles;
INSERT INTO solo_industries (id, name, icon, roles) VALUES ('finance', 'Финансы', '🏦', '["Менеджер банка", "Финансовый консультант"]') ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, icon=EXCLUDED.icon, roles=EXCLUDED.roles;
INSERT INTO solo_industries (id, name, icon, roles) VALUES ('hospitality', 'Сервис', '🛎️', '["Администратор", "Менеджер смены", "Саппорт"]') ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, icon=EXCLUDED.icon, roles=EXCLUDED.roles;
INSERT INTO solo_industries (id, name, icon, roles) VALUES ('public_service', 'Госуслуги', '🏛️', '["Оператор МФЦ", "Инспектор", "Координатор"]') ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, icon=EXCLUDED.icon, roles=EXCLUDED.roles;

-- Seed scenarios
INSERT INTO solo_scenarios (id,industry,skill,title,goal,difficulty,duration_min,xp_reward,coin_reward,ai_persona,patient_type,emoji,script,feedback) VALUES ('med_01','medicine','Сбор анамнеза','Пациент с болью в груди','Сбор анамнеза',2,4,15,8,'Тревожный пациент 55 лет','angry',NULL,'[{"role": "ai", "text": "У меня здесь колет... уже третий день. Что это может быть?", "delay": 1200}, {"role": "user", "expected": ["локализация", "характер боли", "иррадиация"], "hint": "Начните с места боли, характера ощущений и отдаёт ли боль куда-то.", "quickReplies": ["Покажите, где именно болит, какая боль по характеру и отдаёт ли она куда-то?", "Сколько вам лет и принимали ли вы таблетки?"]}, {"role": "ai", "text": "Больше слева. Иногда будто жжёт и уходит в плечо.", "delay": 1400}, {"role": "user", "expected": ["одышка", "тошнота", "пот"], "hint": "Проверьте красные флаги: одышка, тошнота, холодный пот.", "quickReplies": ["Есть ли одышка, тошнота или холодный пот?", "Попробуйте глубоко вдохнуть, стало легче?"]}, {"role": "ai", "text": "Да, сегодня немного тошнило, и я вспотел, когда поднимался по лестнице.", "delay": 1700}, {"role": "user", "expected": ["скорая", "безопасность", "спокойно"], "hint": "Нужно спокойно объяснить срочность и предложить безопасный следующий шаг.", "quickReplies": ["Симптомы требуют срочной оценки. Давайте вызовем скорую, а вы пока сядьте и не нагружайтесь.", "Понаблюдайте до завтра, возможно, пройдёт."]}]','{"good": ["Чётко спросили про локализацию", "Использовали эмпатию", "Отследили красные флаги"], "improve": ["Пропущен вопрос про аллергию", "Слишком быстрый темп"]}') ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title,script=EXCLUDED.script,feedback=EXCLUDED.feedback;
INSERT INTO solo_scenarios (id,industry,skill,title,goal,difficulty,duration_min,xp_reward,coin_reward,ai_persona,patient_type,emoji,script,feedback) VALUES ('med_02','medicine','Эмпатия','Родитель в приёмном покое','Снизить тревогу и собрать симптомы',2,5,16,9,'Мама ребёнка с высокой температурой','sad',NULL,'[{"role": "ai", "text": "У ребёнка 39,5, я уже не знаю, что делать. Почему нас не принимают сразу?", "delay": 1100}, {"role": "user", "expected": ["понимаю", "тревогу", "осмотр"], "hint": "Сначала признайте эмоцию, затем объясните ближайшее действие.", "quickReplies": ["Понимаю вашу тревогу. Сейчас уточню симптомы и помогу ускорить осмотр по приоритету.", "Все ждут, вам нужно успокоиться."]}, {"role": "ai", "text": "Он вялый, почти не пьёт. Я боюсь, что станет хуже.", "delay": 1500}, {"role": "user", "expected": ["пьёт", "мочился", "сыпь"], "hint": "Уточните признаки обезвоживания и опасные симптомы.", "quickReplies": ["Когда он пил последний раз, мочился ли сегодня, есть ли сыпь или судороги?", "Какая температура была утром?"]}, {"role": "ai", "text": "Пил пару глотков, подгузник почти сухой. Сыпи нет.", "delay": 1500}, {"role": "user", "expected": ["передам", "врач", "рядом"], "hint": "Завершите поддержкой и понятным обещанием без ложной гарантии.", "quickReplies": ["Я передам врачу эти признаки прямо сейчас. Оставайтесь рядом, мы не оставим вас без внимания.", "Тогда это не срочно, ждите вызова."]}]','{"good": ["Назвали тревогу родителя", "Собрали признаки обезвоживания", "Дали понятный следующий шаг"], "improve": ["Можно было уточнить вес ребёнка", "Не хватает проверки лекарств и дозировок"]}') ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title,script=EXCLUDED.script,feedback=EXCLUDED.feedback;
INSERT INTO solo_scenarios (id,industry,skill,title,goal,difficulty,duration_min,xp_reward,coin_reward,ai_persona,patient_type,emoji,script,feedback) VALUES ('psy_01','psychology','Активное слушание','Клиент после конфликта','Отразить эмоции и уточнить запрос',1,4,12,7,'Клиент, обиженный на коллегу','neutral',NULL,'[{"role": "ai", "text": "Я сорвался на коллегу. Теперь стыдно, но он тоже перегнул.", "delay": 1200}, {"role": "user", "expected": ["стыд", "злость", "слышится"], "hint": "Отразите две эмоции без оценки.", "quickReplies": ["Слышится, что вам одновременно стыдно и злитесь из-за того, как всё произошло.", "Вы оба виноваты, надо просто извиниться."]}, {"role": "ai", "text": "Да. И я боюсь, что теперь на работе все будут смотреть косо.", "delay": 1300}, {"role": "user", "expected": ["страх", "последствия", "важно"], "hint": "Уточните, какие последствия для клиента самые значимые.", "quickReplies": ["Похоже, вас пугают последствия. Что сейчас для вас самое важное сохранить на работе?", "Почему вас так волнует мнение других?"]}, {"role": "ai", "text": "Хочу восстановить контакт и не выглядеть слабым.", "delay": 1500}, {"role": "user", "expected": ["варианты", "контакт", "границы"], "hint": "Предложите исследовать варианты с учётом контакта и границ.", "quickReplies": ["Давайте рассмотрим варианты, как восстановить контакт и одновременно обозначить границы.", "Лучше сделать вид, что ничего не было."]}]','{"good": ["Отражали чувства без давления", "Уточнили значимый результат", "Сохранили нейтральность"], "improve": ["Можно мягче проверить телесные реакции", "Не стоит торопиться с советами"]}') ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title,script=EXCLUDED.script,feedback=EXCLUDED.feedback;
INSERT INTO solo_scenarios (id,industry,skill,title,goal,difficulty,duration_min,xp_reward,coin_reward,ai_persona,patient_type,emoji,script,feedback) VALUES ('psy_02','psychology','Кризисная коммуникация','Подросток говорит «мне всё равно»','Оценить риск и удержать контакт',3,6,22,12,'Замкнутый подросток 16 лет','sad',NULL,'[{"role": "ai", "text": "Мне всё равно. Никто всё равно не поймёт.", "delay": 1200}, {"role": "user", "expected": ["рядом", "сложно", "расскажешь"], "hint": "Сохраняйте контакт и не спорьте с переживанием.", "quickReplies": ["Похоже, сейчас очень сложно. Я рядом и готов слушать, если расскажешь хотя бы немного.", "Так говорить нельзя, это пугает взрослых."]}, {"role": "ai", "text": "Я просто устал. Иногда думаю, что всем будет легче без меня.", "delay": 1500}, {"role": "user", "expected": ["безопасность", "навредить", "план"], "hint": "Прямо и спокойно оцените риск самоповреждения.", "quickReplies": ["Спасибо, что сказал. Ты думал навредить себе, есть ли план или что-то опасное рядом?", "Не говори так, подумай о родителях."]}, {"role": "ai", "text": "Плана нет, но дома есть таблетки. Я один.", "delay": 1700}, {"role": "user", "expected": ["взрослый", "таблетки", "связь"], "hint": "Нужен ближайший взрослый и удаление опасных предметов.", "quickReplies": ["Давай прямо сейчас свяжемся с взрослым рядом, а таблетки уберём подальше, пока мы на связи.", "Ложись спать, утром станет легче."]}]','{"good": ["Сохранили контакт", "Задали прямой вопрос о риске", "Предложили конкретный план безопасности"], "improve": ["Важно назвать экстренные контакты", "Не хватает согласования следующей проверки связи"]}') ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title,script=EXCLUDED.script,feedback=EXCLUDED.feedback;
INSERT INTO solo_scenarios (id,industry,skill,title,goal,difficulty,duration_min,xp_reward,coin_reward,ai_persona,patient_type,emoji,script,feedback) VALUES ('edu_01','education','Обратная связь','Студент спорит с оценкой','Дать обратную связь без эскалации',2,4,14,8,'Раздражённый студент','angry',NULL,'[{"role": "ai", "text": "Вы занизили оценку. Я потратил на проект всю неделю.", "delay": 1000}, {"role": "user", "expected": ["вижу", "усилия", "критерии"], "hint": "Признайте усилия и переведите разговор к критериям.", "quickReplies": ["Вижу, что вы вложили много усилий. Давайте спокойно пройдёмся по критериям оценки.", "Неделя работы не гарантирует высокий балл."]}, {"role": "ai", "text": "Но у других ошибки были хуже, а баллы выше.", "delay": 1400}, {"role": "user", "expected": ["не сравнивать", "ваша работа", "пример"], "hint": "Не обсуждайте чужие работы, вернитесь к конкретике.", "quickReplies": ["Я не буду сравнивать с чужими работами. Покажу на вашей работе конкретный пример.", "У них были другие обстоятельства."]}, {"role": "ai", "text": "Хорошо, но мне важно понять, как исправить.", "delay": 1300}, {"role": "user", "expected": ["план", "доработка", "срок"], "hint": "Закройте разговор планом доработки и сроком.", "quickReplies": ["Составим короткий план доработки и договоримся о сроке повторной сдачи.", "Прочитайте методичку ещё раз."]}]','{"good": ["Признали усилия", "Опирались на критерии", "Не обсуждали других студентов"], "improve": ["Можно спросить, что студент уже понял сам", "Не хватает одного конкретного примера критерия"]}') ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title,script=EXCLUDED.script,feedback=EXCLUDED.feedback;
INSERT INTO solo_scenarios (id,industry,skill,title,goal,difficulty,duration_min,xp_reward,coin_reward,ai_persona,patient_type,emoji,script,feedback) VALUES ('edu_02','education','Мотивационное интервью','Сотрудник не проходит обучение','Выяснить барьеры и договориться о шаге',2,5,15,9,'Уставший сотрудник на курсе','neutral',NULL,'[{"role": "ai", "text": "Я опять не успел пройти модуль. Честно, не вижу смысла.", "delay": 1200}, {"role": "user", "expected": ["смысл", "мешает", "расскажите"], "hint": "Спросите о барьерах и смысле вместо упрёка.", "quickReplies": ["Расскажите, что больше всего мешает и какой смысл обучения сейчас неочевиден?", "Если не пройдёте, будут последствия."]}, {"role": "ai", "text": "После смены сил нет. А задания кажутся абстрактными.", "delay": 1400}, {"role": "user", "expected": ["пример", "работа", "маленький шаг"], "hint": "Свяжите обучение с реальной задачей и уменьшите шаг.", "quickReplies": ["Давайте возьмём один пример из вашей работы и выберем маленький шаг на 15 минут.", "Нужно просто дисциплинироваться."]}, {"role": "ai", "text": "15 минут звучит реально. Но я могу забыть.", "delay": 1200}, {"role": "user", "expected": ["напоминание", "время", "договоримся"], "hint": "Договоритесь о времени и напоминании.", "quickReplies": ["Договоримся о конкретном времени и включим напоминание перед началом.", "Тогда начните когда получится."]}]','{"good": ["Выяснили барьеры", "Связали обучение с работой", "Предложили реалистичный шаг"], "improve": ["Можно сильнее подчеркнуть автономию сотрудника", "Не хватает проверки согласия на план"]}') ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title,script=EXCLUDED.script,feedback=EXCLUDED.feedback;
INSERT INTO solo_scenarios (id,industry,skill,title,goal,difficulty,duration_min,xp_reward,coin_reward,ai_persona,patient_type,emoji,script,feedback) VALUES ('fin_01','finance','Работа с возражениями','Клиент сомневается в тарифе','Объяснить ценность без давления',2,4,15,8,'Клиент банка, сравнивающий тарифы','vip',NULL,'[{"role": "ai", "text": "У конкурентов обслуживание дешевле. Почему я должен платить больше?", "delay": 1000}, {"role": "user", "expected": ["сравнить", "важно", "задачи"], "hint": "Сначала узнайте, что для клиента важнее цены.", "quickReplies": ["Давайте сравним по вашим задачам: что кроме цены для вас важно в обслуживании?", "Потому что у нас надёжнее."]}, {"role": "ai", "text": "Мне важны быстрые платежи и чтобы поддержка отвечала без очереди.", "delay": 1300}, {"role": "user", "expected": ["платежи", "поддержка", "выгода"], "hint": "Свяжите тариф с названными задачами клиента.", "quickReplies": ["В этом тарифе как раз быстрые платежи и приоритетная поддержка, поэтому выгода не только в цене.", "Тогда берите самый дорогой тариф."]}, {"role": "ai", "text": "А если мне не подойдёт?", "delay": 1200}, {"role": "user", "expected": ["период", "пересмотр", "без давления"], "hint": "Снимите риск через период проверки и отсутствие давления.", "quickReplies": ["Можно начать с периода проверки и потом пересмотреть тариф без давления.", "Если не подойдёт, это уже будет ваш выбор."]}]','{"good": ["Не спорили о цене", "Выявили критерии клиента", "Снизили риск решения"], "improve": ["Можно назвать конкретный срок пересмотра", "Не хватает проверки бюджета"]}') ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title,script=EXCLUDED.script,feedback=EXCLUDED.feedback;
INSERT INTO solo_scenarios (id,industry,skill,title,goal,difficulty,duration_min,xp_reward,coin_reward,ai_persona,patient_type,emoji,script,feedback) VALUES ('fin_02','finance','Объяснение сложного','Инвестор боится просадки','Объяснить риск простым языком',3,6,21,12,'Начинающий инвестор','good',NULL,'[{"role": "ai", "text": "Портфель просел на 8%. Это всё, я потерял деньги?", "delay": 1000}, {"role": "user", "expected": ["понимаю", "просадка", "не зафиксировали"], "hint": "Признайте тревогу и объясните разницу между просадкой и фиксированным убытком.", "quickReplies": ["Понимаю тревогу. Просадка означает снижение стоимости сейчас, но убыток не зафиксирован, пока вы не продали.", "Это нормально, рынок всегда возвращается."]}, {"role": "ai", "text": "Но вдруг упадёт ещё сильнее?", "delay": 1300}, {"role": "user", "expected": ["риск", "горизонт", "диверсификация"], "hint": "Объясните риск через горизонт и диверсификацию.", "quickReplies": ["Такой риск есть, поэтому важны горизонт инвестирования и диверсификация, а не решение в панике.", "Нужно срочно докупить."]}, {"role": "ai", "text": "Что мне делать сегодня?", "delay": 1200}, {"role": "user", "expected": ["план", "цель", "порог"], "hint": "Верните клиента к заранее согласованному плану и порогам.", "quickReplies": ["Сегодня сверим портфель с вашей целью, планом и порогом риска, после этого выберем действие.", "Просто ничего не делайте."]}]','{"good": ["Объяснили термин простыми словами", "Не дали гарантии доходности", "Вернули к плану"], "improve": ["Можно уточнить срок цели", "Стоит проговорить, что это не индивидуальная рекомендация без анализа"]}') ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title,script=EXCLUDED.script,feedback=EXCLUDED.feedback;
INSERT INTO solo_scenarios (id,industry,skill,title,goal,difficulty,duration_min,xp_reward,coin_reward,ai_persona,patient_type,emoji,script,feedback) VALUES ('svc_01','hospitality','Деэскалация','Гость недоволен номером','Снизить напряжение и предложить варианты',2,4,14,8,'Раздражённый гость отеля','angry',NULL,'[{"role": "ai", "text": "В номере шумно и пахнет краской. Я не собираюсь за это платить!", "delay": 1000}, {"role": "user", "expected": ["понимаю", "неприятно", "проверю"], "hint": "Признайте неудобство и возьмите ситуацию в работу.", "quickReplies": ["Понимаю, это неприятно. Я сейчас проверю доступные варианты и помогу решить вопрос.", "У нас все номера такие, ничем не могу помочь."]}, {"role": "ai", "text": "Мне нужен тихий номер сегодня, у меня завтра встреча.", "delay": 1300}, {"role": "user", "expected": ["тихий", "сегодня", "варианты"], "hint": "Повторите приоритет гостя и предложите варианты.", "quickReplies": ["Ваш приоритет - тихий номер уже сегодня. Проверю замену и альтернативные варианты размещения.", "Могу предложить беруши."]}, {"role": "ai", "text": "И что с оплатой за эту ночь?", "delay": 1200}, {"role": "user", "expected": ["компенсация", "правила", "менеджер"], "hint": "Не обещайте лишнего, но обозначьте процесс компенсации.", "quickReplies": ["Я передам менеджеру вопрос компенсации по правилам отеля и вернусь с решением после переселения.", "Вернём всё, только не ругайтесь."]}]','{"good": ["Снизили накал", "Повторили ключевую потребность", "Не дали неподтверждённого обещания"], "improve": ["Можно назвать время ответа менеджера", "Не хватает извинения за конкретное неудобство"]}') ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title,script=EXCLUDED.script,feedback=EXCLUDED.feedback;
INSERT INTO solo_scenarios (id,industry,skill,title,goal,difficulty,duration_min,xp_reward,coin_reward,ai_persona,patient_type,emoji,script,feedback) VALUES ('svc_02','hospitality','Стрессоустойчивость','Клиент кричит в поддержке','Остаться спокойным и вернуть диалог к фактам',3,5,20,11,'Клиент, у которого сорвалась доставка','angry',NULL,'[{"role": "ai", "text": "Вы испортили мне весь день! Где мой заказ? Я требую ответ сейчас!", "delay": 900}, {"role": "user", "expected": ["понимаю", "проверю", "номер заказа"], "hint": "Сохраняйте ровный тон, признайте эмоцию и запросите факт.", "quickReplies": ["Понимаю, ситуация очень неприятная. Я проверю статус, подскажите номер заказа.", "Не кричите, иначе я завершу чат."]}, {"role": "ai", "text": "Номер 4821. И не надо мне ваших шаблонов.", "delay": 1200}, {"role": "user", "expected": ["4821", "минуту", "решение"], "hint": "Подтвердите номер и обозначьте короткое ожидание.", "quickReplies": ["Проверяю заказ 4821, это займёт минуту. После этого предложу решение.", "Я же сказал, ожидайте."]}, {"role": "ai", "text": "Если его нет через час, я пишу жалобу.", "delay": 1400}, {"role": "user", "expected": ["срок", "варианты", "жалоба"], "hint": "Не спорьте с жалобой, дайте срок и варианты.", "quickReplies": ["Вы вправе оставить жалобу. Сейчас уточню реальный срок и предложу варианты: ускорение или компенсация.", "Жалоба ничего не ускорит."]}]','{"good": ["Сохранили спокойный тон", "Вернули разговор к фактам", "Не обесценили право на жалобу"], "improve": ["Можно установить границу общения мягче", "Не хватает финального резюме договорённости"]}') ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title,script=EXCLUDED.script,feedback=EXCLUDED.feedback;
INSERT INTO solo_scenarios (id,industry,skill,title,goal,difficulty,duration_min,xp_reward,coin_reward,ai_persona,patient_type,emoji,script,feedback) VALUES ('gov_01','public_service','Ясные инструкции','Посетитель запутался в документах','Объяснить порядок действий без канцелярита',1,4,12,7,'Пожилой посетитель МФЦ','good',NULL,'[{"role": "ai", "text": "Я уже третий раз прихожу. Опять чего-то не хватает?", "delay": 1100}, {"role": "user", "expected": ["понимаю", "проверим", "список"], "hint": "Сначала снизьте раздражение, затем предложите совместную проверку.", "quickReplies": ["Понимаю, это утомительно. Давайте вместе проверим список документов по шагам.", "Если чего-то нет, придётся прийти ещё раз."]}, {"role": "ai", "text": "У меня паспорт, заявление и копия договора. Что ещё?", "delay": 1200}, {"role": "user", "expected": ["паспорт", "заявление", "выписка"], "hint": "Повторите имеющееся и назовите недостающее простыми словами.", "quickReplies": ["Паспорт, заявление и договор есть. Не хватает выписки, её можно получить в соседнем окне.", "Нужен документ по форме 7-Б."]}, {"role": "ai", "text": "Я могу сделать это сегодня?", "delay": 1000}, {"role": "user", "expected": ["сегодня", "окно", "вернуться"], "hint": "Дайте короткий маршрут и следующий шаг.", "quickReplies": ["Да, сегодня: сначала окно 4 за выпиской, потом вернитесь ко мне, и мы завершим подачу.", "Попробуйте, если успеете."]}]','{"good": ["Говорили простыми словами", "Разложили действия по шагам", "Подтвердили возможность сделать сегодня"], "improve": ["Можно записать маршрут на бумаге", "Не хватает проверки, понял ли посетитель инструкцию"]}') ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title,script=EXCLUDED.script,feedback=EXCLUDED.feedback;
INSERT INTO solo_scenarios (id,industry,skill,title,goal,difficulty,duration_min,xp_reward,coin_reward,ai_persona,patient_type,emoji,script,feedback) VALUES ('gov_02','public_service','Нейтральный тон','Заявитель обвиняет ведомство','Ответить нейтрально и удержать процесс',3,6,21,12,'Заявитель после отказа','neutral',NULL,'[{"role": "ai", "text": "Вы специально всё отклоняете. У вас тут круговая порука!", "delay": 1000}, {"role": "user", "expected": ["понимаю", "расстроены", "причина отказа"], "hint": "Не защищайте систему, верните разговор к причине отказа.", "quickReplies": ["Понимаю, вы расстроены. Давайте разберём конкретную причину отказа и варианты исправления.", "Это необоснованное обвинение."]}, {"role": "ai", "text": "Причина написана непонятно. «Недостаточно оснований» - что это значит?", "delay": 1300}, {"role": "user", "expected": ["простыми словами", "подтверждение", "документ"], "hint": "Переведите формулировку на простой язык.", "quickReplies": ["Простыми словами: не хватает документа, который подтверждает основание для услуги.", "Это юридическая формулировка, она стандартная."]}, {"role": "ai", "text": "И как мне подать снова, чтобы не отказали?", "delay": 1200}, {"role": "user", "expected": ["перечень", "срок", "повторная подача"], "hint": "Назовите перечень, срок и путь повторной подачи.", "quickReplies": ["Я дам перечень документов, срок подготовки и путь повторной подачи через личный кабинет или окно.", "Гарантировать ничего не могу."]}]','{"good": ["Не перешли в спор", "Перевели формулировку на простой язык", "Удержали процесс"], "improve": ["Можно заранее назвать право на обжалование", "Не хватает письменного резюме следующих шагов"]}') ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title,script=EXCLUDED.script,feedback=EXCLUDED.feedback;
INSERT INTO solo_scenarios (id,industry,skill,title,goal,difficulty,duration_min,xp_reward,coin_reward,ai_persona,patient_type,emoji,script,feedback) VALUES ('cross_01','hospitality','Конфликт','Коллега срывает дедлайн','Провести сложный разговор без обвинений',2,5,16,9,'Коллега, который избегает ответственности','neutral',NULL,'[{"role": "ai", "text": "Я не успел свою часть. У меня и так задач выше крыши.", "delay": 1000}, {"role": "user", "expected": ["понимаю", "дедлайн", "влияние"], "hint": "Признайте нагрузку и назовите влияние на общий результат.", "quickReplies": ["Понимаю, нагрузка большая. При этом дедлайн влияет на весь релиз, нужно договориться о плане.", "Ты опять всех подводишь."]}, {"role": "ai", "text": "Ну а что я сделаю, если мне не дали людей?", "delay": 1300}, {"role": "user", "expected": ["ресурсы", "приоритет", "варианты"], "hint": "Соберите факты: ресурсы, приоритеты, варианты сокращения.", "quickReplies": ["Давай посмотрим ресурсы, приоритеты и варианты: что можно сократить или передать?", "Это не моя проблема."]}, {"role": "ai", "text": "Могу отдать черновик сегодня, финал завтра утром.", "delay": 1200}, {"role": "user", "expected": ["фиксируем", "черновик", "завтра"], "hint": "Зафиксируйте договорённость и точное время.", "quickReplies": ["Фиксируем: черновик сегодня, финал завтра утром. Во сколько я получу файл?", "Ладно, только не забудь."]}]','{"good": ["Говорили через влияние, а не обвинение", "Искали варианты", "Зафиксировали договорённость"], "improve": ["Нужно уточнить риск повторного срыва", "Можно договориться о промежуточной проверке"]}') ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title,script=EXCLUDED.script,feedback=EXCLUDED.feedback;
INSERT INTO solo_scenarios (id,industry,skill,title,goal,difficulty,duration_min,xp_reward,coin_reward,ai_persona,patient_type,emoji,script,feedback) VALUES ('cross_02','education','Переговоры','Руководитель просит невозможное','Согласовать реалистичный объём',3,6,22,12,'Руководитель с срочной задачей','vip',NULL,'[{"role": "ai", "text": "Нужно подготовить полный отчёт к вечеру. Это приоритет номер один.", "delay": 1000}, {"role": "user", "expected": ["приоритет", "объём", "срок"], "hint": "Подтвердите приоритет и уточните объём результата к сроку.", "quickReplies": ["Понимаю, это приоритет. Уточню объём: какой результат к вечеру нужен обязательно?", "Это невозможно сделать к вечеру."]}, {"role": "ai", "text": "Мне нужны выводы, таблицы и презентация для совета.", "delay": 1300}, {"role": "user", "expected": ["варианты", "минимум", "качество"], "hint": "Предложите варианты с компромиссом по объёму и качеству.", "quickReplies": ["Есть варианты: к вечеру минимум с выводами и ключевыми таблицами, презентацию доработать утром.", "Если хотите качество, ждите неделю."]}, {"role": "ai", "text": "Хорошо, но выводы должны быть точными.", "delay": 1200}, {"role": "user", "expected": ["данные", "проверка", "согласуем"], "hint": "Закройте договорённость через источник данных и проверку.", "quickReplies": ["Тогда согласуем источники данных и одну проверку в 18:00, чтобы выводы были точными.", "Точность зависит от того, что успею найти."]}]','{"good": ["Не отказались резко", "Предложили реалистичный минимум", "Согласовали проверку качества"], "improve": ["Можно уточнить, что снять с текущих задач", "Не хватает письменного подтверждения договорённости"]}') ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title,script=EXCLUDED.script,feedback=EXCLUDED.feedback;

-- Seed daily suggestions
INSERT INTO daily_suggestions (id,industry,skill,title,description,price,emoji,difficulty,duration_min,patient_type) VALUES ('offer_med_conflict','medicine','Деэскалация','Сложный конфликт в приёмной','Пациент отказывается ждать и требует немедленного приёма. Отработайте спокойный тон и границы.',0,'⚡',2,5,'angry') ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title,description=EXCLUDED.description;
INSERT INTO daily_suggestions (id,industry,skill,title,description,price,emoji,difficulty,duration_min,patient_type) VALUES ('offer_med_chest','medicine','Сбор анамнеза','Боль в груди под давлением','Срочный сбор симптомов при тревоге пациента. Уточните красные флаги и следующий шаг.',5,'🫀',2,4,'vip') ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title,description=EXCLUDED.description;
INSERT INTO daily_suggestions (id,industry,skill,title,description,price,emoji,difficulty,duration_min,patient_type) VALUES ('offer_med_parent','medicine','Эмпатия','Родитель в панике','Мама ребёнка с высокой температурой. Снизьте тревогу и соберите ключевые симптомы.',3,'👶',2,5,'sad') ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title,description=EXCLUDED.description;
INSERT INTO daily_suggestions (id,industry,skill,title,description,price,emoji,difficulty,duration_min,patient_type) VALUES ('offer_psy_crisis','psychology','Кризисная коммуникация','Звонок в кризисной линии','Клиент в остром стрессе. Поддержите, уточните безопасность и предложите план на ближайший час.',8,'📞',3,6,'sad') ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title,description=EXCLUDED.description;
INSERT INTO daily_suggestions (id,industry,skill,title,description,price,emoji,difficulty,duration_min,patient_type) VALUES ('offer_psy_boundaries','psychology','Границы','Клиент нарушает границы','Собеседник давит на личный контакт. Отработайте вежливый отказ и возврат к теме сессии.',5,'🛡️',2,4,'angry') ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title,description=EXCLUDED.description;
INSERT INTO daily_suggestions (id,industry,skill,title,description,price,emoji,difficulty,duration_min,patient_type) VALUES ('offer_edu_parent','education','Обратная связь','Разговор с недовольным родителем','Родитель жалуется на оценки. Дайте конструктивную обратную связь без обороны.',4,'📋',2,5,'angry') ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title,description=EXCLUDED.description;
INSERT INTO daily_suggestions (id,industry,skill,title,description,price,emoji,difficulty,duration_min,patient_type) VALUES ('offer_edu_motivation','education','Мотивация','Студент выгорел','Учащийся потерял интерес. Найдите барьер и согласуйте один маленький шаг.',0,'🌱',1,4,'neutral') ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title,description=EXCLUDED.description;
INSERT INTO daily_suggestions (id,industry,skill,title,description,price,emoji,difficulty,duration_min,patient_type) VALUES ('offer_fin_negotiation','finance','Переговоры','Клиент требует скидку','Лояльный клиент недоволен тарифом. Сохраните отношения и предложите варианты без давления.',6,'💳',2,5,'vip') ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title,description=EXCLUDED.description;
INSERT INTO daily_suggestions (id,industry,skill,title,description,price,emoji,difficulty,duration_min,patient_type) VALUES ('offer_hosp_complaint','hospitality','Работа с жалобой','Гость недоволен номером','Жалоба на шум и сервис. Признайте эмоцию, уточните факты и предложите решение.',3,'🛎️',2,4,'angry') ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title,description=EXCLUDED.description;
INSERT INTO daily_suggestions (id,industry,skill,title,description,price,emoji,difficulty,duration_min,patient_type) VALUES ('offer_hosp_vip','hospitality','VIP-сервис','VIP-гость с особыми запросами','Постоянный клиент просит невозможное. Баланс ожиданий и реальных возможностей отеля.',10,'⭐',3,6,'vip') ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title,description=EXCLUDED.description;
INSERT INTO daily_suggestions (id,industry,skill,title,description,price,emoji,difficulty,duration_min,patient_type) VALUES ('offer_gov_queue','public_service','Ясные инструкции','Очередь в МФЦ','Гражданин не понимает список документов. Объясните простыми словами и зафиксируйте шаги.',0,'🏛️',1,4,'neutral') ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title,description=EXCLUDED.description;
INSERT INTO daily_suggestions (id,industry,skill,title,description,price,emoji,difficulty,duration_min,patient_type) VALUES ('offer_gov_refusal','public_service','Объяснение отказа','Отказ в услуге','Заявитель злится из-за отказа. Объясните причину, документы и путь повторной подачи.',5,'📄',2,5,'angry') ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title,description=EXCLUDED.description;
INSERT INTO daily_suggestions (id,industry,skill,title,description,price,emoji,difficulty,duration_min,patient_type) VALUES ('offer_med_ethics','medicine','Этика','Вопрос о диагнозе соседа','Родственник просит информацию о другом пациенте. Сохраните конфиденциальность и эмпатию.',7,'🔒',3,5,'neutral') ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title,description=EXCLUDED.description;
INSERT INTO daily_suggestions (id,industry,skill,title,description,price,emoji,difficulty,duration_min,patient_type) VALUES ('offer_psy_silence','psychology','Активное слушание','Долгое молчание клиента','Клиент не отвечает на вопросы. Мягко вовлеките без давления и уточняющих «почему».',4,'🤫',2,5,'neutral') ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title,description=EXCLUDED.description;

-- Seed quests
INSERT INTO solo_quests (id,text,reward,type,target_skill) VALUES ('q1','Пройти 1 сценарий на стрессоустойчивость',20,'communication','Стрессоустойчивость') ON CONFLICT (id) DO UPDATE SET text=EXCLUDED.text,reward=EXCLUDED.reward;